### ISSUE TITLE
Werther over HTTPS

### ISSUE THREAD

**Issue by paulb-opusvl** [i-core/werther#9]
**Describe the bug**
I'm struggling to build this container and enable HTTPS on werther. I'm happy that I have it working with HTTP, and now just needs to add the certificates and enable HTTPS.

I created a certificate and used it with hydra and switched that to https, and thought I also need to do this with werther. But I can't figure out how. I even put Nginx in front of it to handle the https and proxy to werther, but it still complains.

It's probably a lack of understanding on my part, but I'd be grateful for any pointers.

**To Reproduce**
My docker-compose.yml
```yaml
version: "3"

services:
  hydra-client:
    image: oryd/hydra:v1.0.0-rc.12
    environment:
      HYDRA_ADMIN_URL: https://hydra:4445
    command:
      - clients
      - create
      - --skip-tls-verify
      - --id
      - ${CLIENT_ID}
      - --secret
      - ${CLIENT_SECRET}
      - --response-types
      - id_token,token,"id_token token"
      - --grant-types
      - implicit
      - --scope
      - openid,profile,email
      - --callbacks
      - ${CALLBACK}
      - --post-logout-callbacks
      - ${CALLBACK_LOGOUT}
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - hydra
    healthcheck:
      test: ["CMD", "curl", "-f", "https://hydra:4445"]
      interval: 10s
      timeout: 10s
      retries: 10

  hydra:
    image: oryd/hydra:v1.0.0-rc.12
    environment:
      URLS_SELF_ISSUER: https://localhost:4444
      URLS_SELF_PUBLIC: https://localhost:4444
      URLS_LOGIN: http://localhost:8080/auth/login
      URLS_CONSENT: http://localhost:8080/auth/consent
      URLS_LOGOUT: http://localhost:8080/auth/logout
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPES: profile,email,phone
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_CLAIMS: name,family_name,given_name,nickname,email,phone_number
      DSN: memory
      HTTPS_TLS_CERT_PATH: ${PWD}/certs/ldap.crt
      HTTPS_TLS_KEY_PATH: ${PWD}/certs/ldap.key
    # command: serve all --dangerous-force-http
    command: serve all
    ports:
      - "4444:4444"
      - "4445:4445"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - werther

  werther:
    image: icoreru/werther:v1.0.0
    environment:
      WERTHER_DEV_MODE: 1
      WERTHER_IDENTP_HYDRA_URL: http://hydra:4445
      WERTHER_ENDPOINTS: ${LDAP_URI}
      WERTHER_LDAP_ENDPOINTS: ${LDAP_URI}
      WERTHER_LDAP_BINDDN: ${LDAP_BINDDN}
      WERTHER_LDAP_BINDPW: ${LDAP_BINDPW}
      WERTHER_LDAP_BASEDN: ${LDAP_BASEDN}
      WERTHER_LDAP_ROLE_BASEDN: "ou=Roles,${LDAP_BASEDN}"
      WERTHER_LDAP_IS_TLS: ${LDAP_TLS}
      WERTHER_LDAP_ATTR_CLAIMS: "cn:name,sn:family_name,givenName:given_name,mail:mail"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
```
**Test URL**

https://localhost:4444/oauth2/auth?client_id=test-client&response_type=token&scope=openid%20profile%20email&state=12345678

**Docker Log Output**
```text
werther_1       | 2020-04-01T13:17:46.884Z      INFO    rlog@v1.0.0/rlog.go:43  New request     {"requestID": "5583550f-ce4b-4d91-b925-25da7a46106d", "method": "GET", "url": "/auth/login?login_challenge=ff6b970735544db9a68f2fb4490054ec"}
werther_1       | 2020-04-01T13:17:46.885Z      INFO    identp/identp.go:128    Failed to initiate an OAuth2 login request      {"requestID": "5583550f-ce4b-4d91-b925-25da7a46106d", "error": "failed to initiate login request: invalid character 'C' looking for beginning of value", "errorVerbose": "invalid character 'C' looking for beginning of value\nfailed to initiate login request\ngithub.com/i-core/werther/internal/hydra.(*LoginReqDoer).InitiateRequest\n\t/opt/build/internal/hydra/login.go:28\ngithub.com/i-core/werther/internal/identp.newLoginStartHandler.func1\n\t/opt/build/internal/identp/identp.go:116\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/i-core/routegroup.(*Router).handler.func1\n\t/go/pkg/mod/github.com/i-core/routegroup@v1.0.0/routegroup.go:65\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334\ngithub.com/i-core/rlog.NewMiddleware.func1.1\n\t/go/pkg/mod/github.com/i-core/rlog@v1.0.0/rlog.go:48\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/justinas/nosurf.(*CSRFHandler).handleSuccess\n\t/go/pkg/mod/github.com/justinas/nosurf@v0.0.0-20171023064657-7182011986c4/handler.go:179\ngithub.com/justinas/nosurf.(*CSRFHandler).ServeHTTP\n\t/go/pkg/mod/github.com/justinas/nosurf@v0.0.0-20171023064657-7182011986c4/handler.go:136\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337", "challenge": "ff6b970735544db9a68f2fb4490054ec"}
werther_1       | 2020-04-01T13:17:46.885Z      DEBUG   rlog@v1.0.0/rlog.go:49  The request is handled  {"requestID": "5583550f-ce4b-4d91-b925-25da7a46106d", "httpStatus": 500, "duration": "1.012755ms"}
werther_1       | 2020-04-01T13:17:46.948Z      INFO    rlog@v1.0.0/rlog.go:43  New request     {"requestID": "8a455c6d-ef60-4d2e-ac01-d95d5227fa93", "method": "GET", "url": "/favicon.ico"}
werther_1       | 2020-04-01T13:17:46.948Z      DEBUG   rlog@v1.0.0/rlog.go:49  The request is handled  {"requestID": "8a455c6d-ef60-4d2e-ac01-d95d5227fa93", "httpStatus": 404, "duration": "5.242µs"}
```

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser Firefox
 - Version 74.0

**Comment by nikolaas** [comment]
Hello. Sorry for the late answer.

Now Werther can't serve requests over HTTPS. But you are right. You can configure Nginx as an HTTPS reverse proxy and put it in front of Werther. This is an example of `docker-compose.yaml`:

```yaml
version: "3"

services:
  hydra-client:
    image: oryd/hydra:v1.0.0-rc.12
    environment:
      HYDRA_ADMIN_URL: https://hydra:4445
    networks:
      - hydra-net
    command:
      - clients
      - create
      - --skip-tls-verify
      - --id
      - test-client
      - --secret
      - qwerty
      - --response-types
      - id_token,token,"id_token token"
      - --grant-types
      - implicit
      - --scope
      - openid,profile,email
      - --callbacks
      - http://localhost:9000/auth-callback
      - --post-logout-callbacks
      - http://localhost:9000
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - hydra
    healthcheck:
      test: ["CMD", "curl", "-k",  "-f", "https://hydra:4445"]
      interval: 10s
      timeout: 10s
      retries: 10

  hydra:
    image: oryd/hydra:v1.0.0-rc.12
    volumes:
      - "/path/to/cert.crt:/hydra/cert.crt"
      - "/path/to/key.pem:/hydra/key.pem"
    environment:
      URLS_SELF_ISSUER: https://localhost:4444
      URLS_SELF_PUBLIC: https://localhost:4444
      URLS_LOGIN: https://localhost/auth/login
      URLS_CONSENT: https://localhost/auth/consent
      URLS_LOGOUT: https://localhost/auth/logout
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPES: profile,email,phone
      WEBFINGER_OIDC_DISCOVERY_SUPPORTED_CLAIMS: name,family_name,given_name,nickname,email,phone_number
      DSN: memory
      SERVE_TLS_CERT_PATH: /hydra/cert.crt
      SERVE_TLS_KEY_PATH: /hydra/key.pem
    command: serve all
    networks:
      - hydra-net
    ports:
      - "4444:4444"
      - "4445:4445"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - werther-proxy

  werther-proxy:
    image: nginx:alpine
    volumes:
      - "/path/to/cert.crt:/etc/ssl/certs/server.crt"
      - "/path/to/key.pem:/etc/ssl/certs/server.key"
      - "/path/to/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - hydra-net
    ports:
      - "443:443"
    depends_on:
      - werther

  werther:
    image: icoreru/werther:1.0.1
    environment:
      WERTHER_DEV_MODE: "true"
      WERTHER_IDENTP_HYDRA_URL: https://hydra:4445
      WERTHER_LDAP_ENDPOINTS: ldap:389
      WERTHER_LDAP_BINDDN: cn=admin,dc=example,dc=com
      WERTHER_LDAP_BINDPW: password
      WERTHER_LDAP_BASEDN: "dc=example,dc=com"
      WERTHER_LDAP_ROLE_BASEDN: "ou=AppRoles,dc=example,dc=com"
    networks:
      - hydra-net
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - ldap

  ldap:
    image: pgarrett/ldap-alpine
    volumes:
      - "./ldap.ldif:/ldif/ldap.ldif"
    networks:
      - hydra-net
    ports:
      - "389:389"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  hydra-net:
```

And an example of `nginx.conf`:
```yaml
worker_processes  1;

events {
    worker_connections  1024;
}

http {

    error_log stderr;
    access_log /dev/stdout;

    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen      443 ssl;
        server_name localhost;

        ssl_certificate        /etc/ssl/certs/server.crt;
        ssl_certificate_key    /etc/ssl/certs/server.key;
        ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers  "RC4:HIGH:!aNULL:!MD5:!kEDH";

        location / {
            proxy_pass http://werther:8080;
        }
    }

}
```

There is one note. Werther uses `http.DefaultClient` to communicate with the Ory Hydra server. `http.DefaultClient` accepts only trusted certificates. So the certificate you provide Wether should be signed by one of the CAs or installed as a trusted certificate.

P.S. HTTPS support is coming.
